import os
import sys
import datetime

# HEPHAESTUS - The Skill Generator
# Usage: python generate_skill.py <skill_name> "<description>"

def create_file(path, content):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content.strip())
    print(f"✅ Created: {path}")

def generate_skill(name, description):
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../skills'))
    skill_dir = os.path.join(root_dir, name)

    if os.path.exists(skill_dir):
        print(f"❌ Error: Skill '{name}' already exists at {skill_dir}")
        sys.exit(1)

    # 1. Create Skeleton
    os.makedirs(os.path.join(skill_dir, 'scripts'), exist_ok=True)
    os.makedirs(os.path.join(skill_dir, 'examples'), exist_ok=True)
    os.makedirs(os.path.join(skill_dir, 'tests'), exist_ok=True) # Mandatory for Hephaestus Protocol

    # 2. Forge DNA (SKILL.md)
    skill_md_content = f"""---
name: {name}
description: {description}
---

# {name.replace('_', ' ').title()} (Agent Skill)

## 🎯 Purpose
[Describe the core mission of this skill. e.g., "Manage YouTube uploads and analytics."]

## 🛠️ Capabilities
*   **Action 1**: [Description]
*   **Action 2**: [Description]

## 📋 Instructions
1.  **Step 1**: [Instruction]
2.  **Step 2**: [Instruction]

## 🛡️ Self-Correction Rules
*   [ ] Verify input data before processing.
*   [ ] If API fails, retry 3 times with exponential backoff.
*   [ ] Log all critical actions to `SYSTEM_STATE_LOG.md`.

## 🧠 Memory & Context
*   **Reads**: [Files this skill needs to read]
*   **Writes**: [Files this skill generates]

## 🤖 Example Usage
User: "Run the {name.replace('_', ' ')} task"
Agent: Checks requirements -> Executes script -> Reports result.
"""
    create_file(os.path.join(skill_dir, 'SKILL.md'), skill_md_content)

    # 3. Forge Hands (Placeholder Script)
    script_content = f"""
# {name.upper()} HANDLER
# Generated by Skill Forge on {datetime.date.today()}

def execute():
    print(f"🔧 {name}: Logic not implemented yet.")
    # TODO: Implement core logic here

if __name__ == "__main__":
    execute()
"""
    create_file(os.path.join(skill_dir, f'scripts/{name}_handler.py'), script_content)

    # 4. Forge Conscience (Self-Audit Test)
    test_content = f"""
# {name.upper()} SELF-AUDIT
# Generated by Skill Forge on {datetime.date.today()}
import pytest
import sys
import os

# Add scripts folder to path
sys.path.append(os.path.join(os.path.dirname(__file__), '../scripts'))

try:
    import {name}_handler
except ImportError:
    pytest.fail("Could not import {name}_handler. Check directory structure.")

def test_import():
    assert {name}_handler is not None
    print("✅ {name}_handler imported successfully.")

if __name__ == "__main__":
    test_import()
"""
    create_file(os.path.join(skill_dir, 'tests/test_setup.py'), test_content)

    print(f"\n✨ Skill '{name}' forged successfully!")
    print(f"📂 Location: {skill_dir}")
    print("👉 Next Step: Edit SKILL.md to define specific logic.")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python generate_skill.py <skill_name> \"<description>\"")
        sys.exit(1)
    
    generate_skill(sys.argv[1], sys.argv[2])
