-- ⚛️ THE NUCLEUS V5.3 DIAMOND CUT (FINAL PRODUCTION)
-- Generated by Antigravity
-- Target: Supabase (PostgreSQL 15+)
-- 
-- CHANGELOG V5.3 (Diamond Cut):
-- 1. IDEMPOTENCY: Added DROP POLICY IF EXISTS.
-- 2. NULLABLE DIFF: `diff_log` accepts NULL (no changes) or Array.
-- 3. TRIPLE JUSTIFICATION: Restored `knowledge` and `math` columns.
-- 4. SEED DATA: Added ORION_V3_4 to Registry to prevent FK errors.

BEGIN;

-- =================================================================
-- 0. CLEANUP & EXTENSIONS
-- =================================================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =================================================================
-- 1. STRICT ENUMS
-- =================================================================
DO $$ BEGIN
    CREATE TYPE ag_platform_type AS ENUM ('Desktop', 'Mobile_iOS', 'Mobile_Android', 'API_Headless');
    CREATE TYPE ag_session_phase AS ENUM ('PLANNING', 'RESEARCH', 'SCRIPTING', 'PRODUCTION', 'AUDIT', 'PUBLISHING');
    CREATE TYPE ag_agent_status AS ENUM ('IDLE', 'ACTIVE', 'PAUSED', 'ERROR', 'SLEEPING');
    CREATE TYPE ag_asset_type AS ENUM ('SCRIPT_MD', 'VIDEO_MP4', 'AUDIO_WAV', 'IMAGE_PNG', 'THUMBNAIL_JPG', 'METADATA_JSON', 'IDEA_JSON', 'TREND_REPORT', 'AUDIT_REPORT');
    CREATE TYPE ag_decision_type AS ENUM ('RANKING', 'HOOK_SELECTION', 'VISUAL_STYLE', 'TREND_ANALYSIS', 'SAFETY_GATE');
    CREATE TYPE ag_command_type AS ENUM ('START', 'PAUSE', 'RESUME', 'STOP', 'EDIT_MEMORY', 'ROLLBACK');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- =================================================================
-- 2. CONTROL PLANE (IDENTITY & GOVERNANCE)
-- =================================================================

CREATE TABLE IF NOT EXISTS ag_agent_registry (
    id text PRIMARY KEY, -- 'ORION_V3_4'
    name text NOT NULL,
    version text NOT NULL,
    role_description text,
    allowed_phases ag_session_phase[] NOT NULL,
    config_schema jsonb,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE ag_agent_registry ENABLE ROW LEVEL SECURITY;

-- Policy: Public Read (Authenticated), Admin Write (Service Only)
DROP POLICY IF EXISTS "Public Read Agents" ON ag_agent_registry;
CREATE POLICY "Public Read Agents" ON ag_agent_registry FOR SELECT TO authenticated USING (true);

-- SEED DATA
INSERT INTO ag_agent_registry (id, name, version, role_description, allowed_phases, config_schema)
VALUES (
  'ORION_V3_4',
  'Orion',
  '3.4.0',
  'Investment Analyst of Attention',
  ARRAY['PLANNING','RESEARCH','SCRIPTING','PRODUCTION','AUDIT','PUBLISHING']::ag_session_phase[],
  '{}'::jsonb
)
ON CONFLICT (id) DO NOTHING;


-- =================================================================
-- 3. ORCHESTRATION LAYER (SESSIONS)
-- =================================================================

CREATE TABLE IF NOT EXISTS ag_sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id uuid REFERENCES auth.users NOT NULL,
    
    platform ag_platform_type NOT NULL DEFAULT 'Desktop',
    active_agent_id text REFERENCES ag_agent_registry(id),
    current_phase ag_session_phase DEFAULT 'PLANNING',
    current_status ag_agent_status DEFAULT 'ACTIVE',
    
    -- Financials
    accumulated_cost numeric(10,4) DEFAULT 0.0000,
    currency char(3) DEFAULT 'USD',
    
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

ALTER TABLE ag_sessions ENABLE ROW LEVEL SECURITY;

-- INDEX: Performance
CREATE INDEX IF NOT EXISTS idx_sessions_user_created ON ag_sessions (user_id, created_at DESC);

-- POLICY: CRUD for Owner
DROP POLICY IF EXISTS "Owner Access Sessions" ON ag_sessions;
CREATE POLICY "Owner Access Sessions" ON ag_sessions 
    FOR ALL 
    TO authenticated 
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Trigger: Updated_At
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language plpgsql;

DROP TRIGGER IF EXISTS update_ag_sessions_modtime ON ag_sessions;
CREATE TRIGGER update_ag_sessions_modtime
    BEFORE UPDATE ON ag_sessions
    FOR EACH ROW EXECUTE FUNCTION update_modified_column();

-- =================================================================
-- 4. CONTROL EVENTS (IMMUTABLE LOG)
-- =================================================================

CREATE TABLE IF NOT EXISTS ag_control_events (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_id uuid REFERENCES ag_sessions NOT NULL,
    command_type ag_command_type NOT NULL, 
    payload jsonb,
    issued_by uuid REFERENCES auth.users,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE ag_control_events ENABLE ROW LEVEL SECURITY;

-- INDEX: Timeline
CREATE INDEX IF NOT EXISTS idx_events_session_created ON ag_control_events (session_id, created_at DESC);

-- POLICY: Owner Access
DROP POLICY IF EXISTS "Owner Select Events" ON ag_control_events;
DROP POLICY IF EXISTS "Owner Insert Events" ON ag_control_events;
DROP POLICY IF EXISTS "Owner View Events" ON ag_control_events; -- Old name cleanup

CREATE POLICY "Owner Select Events" ON ag_control_events
    FOR SELECT TO authenticated
    USING (session_id IN (SELECT id FROM ag_sessions WHERE user_id = auth.uid()));

CREATE POLICY "Owner Insert Events" ON ag_control_events
    FOR INSERT TO authenticated
    WITH CHECK (session_id IN (SELECT id FROM ag_sessions WHERE user_id = auth.uid()));

-- =================================================================
-- 5. INTELLIGENCE LAYER (PARTITIONED MEMORY)
-- =================================================================

CREATE TABLE IF NOT EXISTS ag_agent_memory (
    session_id uuid REFERENCES ag_sessions NOT NULL,
    agent_id text REFERENCES ag_agent_registry(id) NOT NULL,
    captured_at timestamptz DEFAULT now(),
    id bigint GENERATED ALWAYS AS IDENTITY,
    
    memory_snapshot jsonb NOT NULL, 
    
    -- RFC 6902 Checker (Nullable)
    diff_log jsonb CHECK (diff_log IS NULL OR jsonb_typeof(diff_log) = 'array'), 
    
    -- FORENSIC PK: Session + Time + ID
    PRIMARY KEY (session_id, captured_at, id)
) PARTITION BY RANGE (captured_at);

ALTER TABLE ag_agent_memory ENABLE ROW LEVEL SECURITY;

-- INDEX: Timeline
CREATE INDEX IF NOT EXISTS idx_memory_session_captured ON ag_agent_memory (session_id, captured_at DESC);

-- POLICIES
DROP POLICY IF EXISTS "Owner Read Memory" ON ag_agent_memory;
CREATE POLICY "Owner Read Memory" ON ag_agent_memory
    FOR SELECT TO authenticated
    USING (session_id IN (SELECT id FROM ag_sessions WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Owner Insert Memory" ON ag_agent_memory;
CREATE POLICY "Owner Insert Memory" ON ag_agent_memory
    FOR INSERT TO authenticated
    WITH CHECK (session_id IN (SELECT id FROM ag_sessions WHERE user_id = auth.uid()));

-- PARTITION: Default (Safety Net)
CREATE TABLE IF NOT EXISTS ag_agent_memory_default PARTITION OF ag_agent_memory DEFAULT;

-- PARTITIONS: Monthly
CREATE TABLE IF NOT EXISTS ag_agent_memory_y2026m01 PARTITION OF ag_agent_memory
    FOR VALUES FROM ('2026-01-01') TO ('2026-02-01');
CREATE TABLE IF NOT EXISTS ag_agent_memory_y2026m02 PARTITION OF ag_agent_memory
    FOR VALUES FROM ('2026-02-01') TO ('2026-03-01');
CREATE TABLE IF NOT EXISTS ag_agent_memory_y2026m03 PARTITION OF ag_agent_memory
    FOR VALUES FROM ('2026-03-01') TO ('2026-04-01');

-- =================================================================
-- 6. LOGIC TRACE (STRICT W3C + INTEGRITY)
-- =================================================================

CREATE TABLE IF NOT EXISTS ag_logic_trace (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_id uuid REFERENCES ag_sessions NOT NULL,
    agent_id text REFERENCES ag_agent_registry(id) NOT NULL,
    
    -- Strict W3C Checks
    trace_id char(32) NOT NULL CHECK (trace_id ~ '^[a-f0-9]{32}$'),
    span_id char(16) NOT NULL CHECK (span_id ~ '^[a-f0-9]{16}$'),
    parent_span_id char(16) CHECK (parent_span_id ~ '^[a-f0-9]{16}$'),
    
    decision_type ag_decision_type NOT NULL,
    
    -- FORENSIC COMPOSITE FK (Includes Session ID)
    input_snapshot_captured_at timestamptz,
    input_snapshot_id bigint,
    
    FOREIGN KEY (session_id, input_snapshot_captured_at, input_snapshot_id) 
        REFERENCES ag_agent_memory (session_id, captured_at, id),
    
    -- Triple Justification Protocol (Restored)
    justification_identity text,
    justification_knowledge text,
    justification_math text,
    
    confidence_score numeric(3,2) CHECK (confidence_score BETWEEN 0.00 AND 1.00),
    auto_corrected boolean DEFAULT false,
    
    created_at timestamptz DEFAULT now()
);

ALTER TABLE ag_logic_trace ENABLE ROW LEVEL SECURITY;

-- INDEX: Timeline
CREATE INDEX IF NOT EXISTS idx_trace_session_created ON ag_logic_trace (session_id, created_at DESC);

-- POLICY
DROP POLICY IF EXISTS "Owner Read Traces" ON ag_logic_trace;
CREATE POLICY "Owner Read Traces" ON ag_logic_trace
    FOR SELECT TO authenticated
    USING (session_id IN (SELECT id FROM ag_sessions WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Owner Insert Traces" ON ag_logic_trace;
CREATE POLICY "Owner Insert Traces" ON ag_logic_trace
    FOR INSERT TO authenticated
    WITH CHECK (session_id IN (SELECT id FROM ag_sessions WHERE user_id = auth.uid()));

-- =================================================================
-- 7. ASSET LAYER
-- =================================================================

CREATE TABLE IF NOT EXISTS ag_assets (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id uuid REFERENCES ag_sessions,
    title text NOT NULL,
    asset_type ag_asset_type NOT NULL,
    version int4 DEFAULT 1,
    created_by_agent text REFERENCES ag_agent_registry(id),
    storage_path text NOT NULL,
    production_cost numeric(10,4) DEFAULT 0.0000,
    roi_actual numeric(10,4),
    created_at timestamptz DEFAULT now()
);

ALTER TABLE ag_assets ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_assets_session_created ON ag_assets (session_id, created_at DESC);

DROP POLICY IF EXISTS "Owner CRUD Assets" ON ag_assets;
CREATE POLICY "Owner CRUD Assets" ON ag_assets
    FOR ALL TO authenticated
    USING (session_id IN (SELECT id FROM ag_sessions WHERE user_id = auth.uid()))
    WITH CHECK (session_id IN (SELECT id FROM ag_sessions WHERE user_id = auth.uid()));

-- =================================================================
-- 8. FEEDBACK LAYER
-- =================================================================

CREATE TABLE IF NOT EXISTS ag_social_metrics (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    asset_id uuid REFERENCES ag_assets NOT NULL,
    platform text,
    views numeric(20,0),
    captured_at timestamptz DEFAULT now()
);

ALTER TABLE ag_social_metrics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Owner CRUD Metrics" ON ag_social_metrics;
CREATE POLICY "Owner CRUD Metrics" ON ag_social_metrics
    FOR ALL TO authenticated
    USING (asset_id IN (SELECT id FROM ag_assets WHERE session_id IN (SELECT id FROM ag_sessions WHERE user_id = auth.uid())))
    WITH CHECK (asset_id IN (SELECT id FROM ag_assets WHERE session_id IN (SELECT id FROM ag_sessions WHERE user_id = auth.uid())));

COMMIT;
