# NOTEBOOKLM_MASTERY SELF-AUDIT
# Generated by Skill Forge on 2026-02-08
import pytest
import sys
import os

# Add scripts folder to path
sys.path.append(os.path.join(os.path.dirname(__file__), '../scripts'))

try:
    import notebooklm_mastery_handler
except ImportError:
    pytest.fail("Could not import notebooklm_mastery_handler. Check directory structure.")

def test_import():
    assert notebooklm_mastery_handler is not None
    print("✅ notebooklm_mastery_handler imported successfully.")

if __name__ == "__main__":
    test_import()